services:
  db:
    image: postgres:16-alpine
    container_name: rev_engine_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rev_engine
    ports:
      - "5433:5432"
    volumes:
      - rev_engine_db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: rev_engine_api
    depends_on:
      - db
    env_file:
      - .env
    environment:

      DATABASE_URL: postgresql://postgres.fkyqtgczjgmoweppxrdz:FQSyT2An9aj1q32a@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
      PORT: 8000
      CLIENT_URL: http://localhost:5173
      # Optional. Leave empty unless you want backend to prefix relative media paths.

    ports:
      - "8000:8000"

volumes:
  rev_engine_db_data:

